<?php

namespace Database\Seeders;

use App\Models\Treatment;
use Illuminate\Database\Seeder;

class TreatmentSeeder extends Seeder
{
    /**
     * Seed the existing homepage treatments into the database.
     */
    public function run(): void
    {
        foreach ($this->treatments() as $treatment) {
            $treatment = $this->withSeoDefaults($treatment);

            Treatment::updateOrCreate(
                ['slug' => $treatment['slug']],
                $treatment,
            );
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function treatments(): array
    {
        return [
            [
                'sort_order' => 1,
                'is_active' => true,
                'slug' => 'painless-dentistry',
                'tone' => 'crimson',
                'home_title' => 'Painless Dentistry',
                'home_subtitle' => 'Comfort first, always.',
                'home_description' => 'Numbing before the needle, computer-controlled delivery and a hand signal that stops everything the moment you raise it.',
                'home_image' => '/assets/elderly-care.jpg',
                'home_image_alt' => 'A patient relaxed in the chair during treatment',
                'home_icon_svg' => '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
                'category' => 'Comfort dentistry',
                'title' => 'Painless Dentistry',
                'title_accent' => 'Dentistry',
                'tagline' => 'Comfort first, always.',
                'summary' => 'Dental care planned around calm, control and clear pauses. We numb carefully, work slowly, and agree on a stop signal before treatment begins.',
                'hero_image' => '/assets/elderly-care.jpg',
                'hero_image_alt' => 'A patient relaxed in the chair during treatment',
                'facts' => [
                    ['label' => 'Best for', 'value' => 'Anxious patients'],
                    ['label' => 'Visit style', 'value' => 'Unhurried'],
                    ['label' => 'Anaesthesia', 'value' => 'Planned first'],
                    ['label' => 'Control', 'value' => 'Stop signal'],
                ],
                'overview_eyebrow' => 'What it is',
                'overview_heading' => 'Dentistry that does not ask you to be brave.',
                'overview_heading_accent' => 'brave',
                'overview_lede' => 'The appointment is built so you know what is happening, how long it will take, and how to pause it at any point.',
                'overview_body' => "Painless dentistry starts before the instrument touches a tooth. We talk through the plan, numb the area gently, and wait until the anaesthetic has properly worked before moving ahead.\n\nFor patients who dislike injections, we use topical numbing first and deliver anaesthetic slowly. The aim is not speed. The aim is a visit where your jaw, shoulders and breathing can stay relaxed.\n\nIf something feels sharp, pressured or simply too much, the hand signal stops the appointment immediately. That rule matters most for people who have avoided dental care because of one bad experience.",
                'overview_image' => '/assets/consult-family.jpg',
                'overview_image_alt' => 'A dentist explaining a treatment plan to a patient',
                'overview_caption' => 'The plan is explained before treatment, with pauses agreed before we begin.',
                'suitability_eyebrow' => 'Suitability',
                'suitability_heading' => 'Who this works for.',
                'suitability_heading_accent' => 'works',
                'suitability_lede' => 'A comfort-led appointment is useful for almost any treatment, but especially when fear has delayed care.',
                'suitable_for' => [
                    ['text' => 'Patients who feel anxious before dental visits'],
                    ['text' => 'Long appointments that need planned breaks'],
                    ['text' => 'People with a strong gag reflex or needle fear'],
                    ['text' => 'Children or adults rebuilding trust after a difficult visit'],
                    ['text' => 'Treatment that needs local anaesthesia to work predictably'],
                ],
                'not_suitable' => [
                    ['text' => 'Cases where pain comes from an active infection that must be treated first'],
                    ['text' => 'Patients who need hospital sedation or general anaesthesia'],
                    ['text' => 'Appointments where medical history has not yet been reviewed'],
                    ['text' => 'Severe swelling or fever, which needs urgent clinical assessment'],
                ],
                'process_eyebrow' => 'Step by step',
                'process_heading' => 'From nervous arrival to finished care.',
                'process_heading_accent' => 'finished',
                'process_lede' => 'The visit is paced deliberately. Most of the work is making the appointment predictable before treatment begins.',
                'steps' => [
                    ['title' => 'Conversation first', 'duration' => '10-15 minutes', 'body' => 'We ask what has made dentistry difficult before, then agree on the treatment plan, the stop signal and where breaks should happen.'],
                    ['title' => 'Gentle numbing', 'duration' => 'As needed', 'body' => 'Topical gel is used before anaesthetic, and the injection is delivered slowly so the area becomes numb without rushing.'],
                    ['title' => 'Confirm comfort', 'duration' => 'Before treatment', 'body' => 'We test the tooth and surrounding gum before beginning. If you can still feel sharpness, we wait or add more anaesthetic.'],
                    ['title' => 'Treatment with pauses', 'duration' => 'Varies by care', 'body' => 'The appointment moves in short sections. You can stop the chair at any point using the agreed signal.'],
                    ['title' => 'Aftercare instructions', 'duration' => '5 minutes', 'body' => 'You leave knowing what is normal, what is not, and who to call if the numbness or soreness does not settle as expected.'],
                ],
                'faq_eyebrow' => 'Questions',
                'faq_heading' => 'The things people actually ask.',
                'faq_heading_accent' => 'ask',
                'faq_lede' => 'If fear is the reason you have delayed treatment, say so at the start. It changes how we plan the visit.',
                'faqs' => [
                    ['question' => 'Will I feel the injection?', 'answer' => 'Topical numbing is used first, and the anaesthetic is delivered slowly. Most patients describe pressure more than pain.'],
                    ['question' => 'Can I stop during treatment?', 'answer' => 'Yes. A hand signal is agreed before we start, and treatment stops immediately when you use it.'],
                    ['question' => 'Do you offer sedation?', 'answer' => 'This page covers comfort-led local dental care. If you need hospital sedation or general anaesthesia, we will discuss the appropriate referral route.'],
                    ['question' => 'Can this approach be used for root canals or extractions?', 'answer' => 'Yes, the same comfort principles apply. The exact anaesthetic plan depends on the tooth, infection status and medical history.'],
                ],
                'cta_heading' => 'Find out if it is right for you.',
                'cta_heading_accent' => 'right',
                'cta_body' => 'Book a consultation and tell us what has made previous dental visits difficult. The plan can be paced around that.',
                'whatsapp_number' => '919820000000',
                'whatsapp_message' => "Hi, I'd like to ask about painless dentistry.",
                'phone' => '+912226000000',
                'seo_title' => "Painless Dentistry - Dr. Pushpa Patel's Dental Clinic",
                'seo_description' => 'Painless dentistry focused on gentle anaesthesia, clear pauses and calm dental care at Dr. Pushpa Patel Dental Clinic.',
            ],
            [
                'sort_order' => 2,
                'is_active' => true,
                'slug' => 'dental-implants',
                'tone' => 'ink',
                'home_title' => 'Dental Implants',
                'home_subtitle' => 'Permanent teeth, precisely placed.',
                'home_description' => 'Guided placement from a CBCT-planned stent, with provisional teeth the same day wherever the bone allows it.',
                'home_image' => '/assets/planning.jpg',
                'home_image_alt' => 'Digital implant planning on screen',
                'home_icon_svg' => '<path d="M12 3c-3 0-4.6 1.9-4.6 4.6 0 2.2.8 3.4.8 6.2 0 1.9-.6 3.4-.6 5.1 0 1.4.7 2.1 1.7 2.1 1.9 0 1.6-4.4 2.7-4.4s.8 4.4 2.7 4.4c1 0 1.7-.7 1.7-2.1 0-1.7-.6-3.2-.6-5.1 0-2.8.8-4 .8-6.2C16.6 4.9 15 3 12 3z"/>',
                'category' => 'Restorative dentistry',
                'title' => 'Dental Implants',
                'title_accent' => 'Implants',
                'tagline' => 'Permanent teeth, precisely placed.',
                'summary' => 'A titanium root placed from a CBCT-planned guide, carrying a ceramic tooth built to match the teeth around it. Planned, placed and finished with the same clinical team.',
                'hero_image' => '/assets/planning.jpg',
                'hero_image_alt' => 'Digital implant planning on screen',
                'facts' => [
                    ['label' => 'Treatment time', 'value' => '60-90 min'],
                    ['label' => 'Visits needed', 'value' => '3 to 4'],
                    ['label' => 'Anaesthesia', 'value' => 'Local'],
                    ['label' => 'Typically lasts', 'value' => '15+ years'],
                ],
                'overview_eyebrow' => 'What it is',
                'overview_heading' => 'A tooth that behaves like a tooth.',
                'overview_heading_accent' => 'like a tooth',
                'overview_lede' => 'An implant is anchored in bone, so you bite, chew and clean it the way you would the tooth it replaced.',
                'overview_body' => "An implant has three parts: a titanium post that takes the place of the root, an abutment at gum level, and the ceramic crown you see when you smile.\n\nA CBCT scan maps the bone, nerve and sinus in three dimensions. That scan guides the final position before the appointment, so the implant is not placed by guesswork.\n\nWhere the bone allows it, a provisional tooth can be fitted early. Where it does not, the timeline is explained at the planning visit rather than discovered during surgery.",
                'overview_image' => '/assets/consult-family.jpg',
                'overview_image_alt' => 'A dentist talking a patient through a panoramic X-ray on screen',
                'overview_caption' => 'Your scan goes up on the screen next to the chair before any treatment is agreed.',
                'suitability_eyebrow' => 'Suitability',
                'suitability_heading' => 'Who this works for.',
                'suitability_heading_accent' => 'works',
                'suitability_lede' => 'Implants work best when the gums are healthy and there is enough bone to support the planned position.',
                'suitable_for' => [
                    ['text' => 'A single missing tooth where you want to avoid filing adjacent teeth'],
                    ['text' => 'Several gaps in one arch, or a bridge that has failed'],
                    ['text' => 'A lower denture that will not stay put'],
                    ['text' => 'A tooth cracked below the gum that cannot be saved'],
                    ['text' => 'Healthy gums and enough bone, or bone that can be grafted'],
                ],
                'not_suitable' => [
                    ['text' => 'Active gum disease, which should be settled first'],
                    ['text' => 'Uncontrolled diabetes until levels are stable'],
                    ['text' => 'Current smoking, which lowers the success rate'],
                    ['text' => 'Jaws that are still growing'],
                    ['text' => 'Certain bone medications that need medical review first'],
                ],
                'process_eyebrow' => 'Step by step',
                'process_heading' => 'From scan to finished tooth.',
                'process_heading_accent' => 'finished tooth',
                'process_lede' => 'Most implant plans are spread over several months. Much of that time is healing, not chair time.',
                'steps' => [
                    ['title' => 'Consultation and CBCT scan', 'duration' => '60 minutes', 'body' => 'We examine, scan and go through the 3D images with you. You leave with a written plan and expected cost.'],
                    ['title' => 'Digital planning', 'duration' => '5-7 days', 'body' => 'The implant position is planned around the nerve, sinus and final tooth shape before the placement visit.'],
                    ['title' => 'Placement', 'duration' => '60-90 minutes', 'body' => 'Local anaesthetic is used, the guide is checked, and the implant is placed according to the digital plan.'],
                    ['title' => 'Healing and integration', 'duration' => '8-12 weeks', 'body' => 'Bone grows onto the implant surface. A provisional tooth may be used where the plan allows it.'],
                    ['title' => 'The permanent crown', 'duration' => '2 visits', 'body' => 'We scan, shade-match and fit the ceramic crown. You approve the look before it is finally tightened.'],
                ],
                'faq_eyebrow' => 'Questions',
                'faq_heading' => 'The things people actually ask.',
                'faq_heading_accent' => 'ask',
                'faq_lede' => 'If your question is not here, call the clinic and bring your X-rays or scans if you have them.',
                'faqs' => [
                    ['question' => 'Does implant placement hurt?', 'answer' => 'The placement is done under local anaesthetic. Most patients describe the recovery as similar to, or easier than, the extraction that came before it.'],
                    ['question' => 'How long do implants last?', 'answer' => 'The implant is designed for long-term use. The crown on top is the part that may wear and need replacement later, similar to other crowns.'],
                    ['question' => 'What if I do not have enough bone?', 'answer' => 'Bone grafting is often possible. The CBCT scan tells us before treatment whether grafting is needed and whether it can be done at the same appointment.'],
                    ['question' => 'Can I get a tooth the same day?', 'answer' => 'Sometimes. A provisional tooth can be fitted when the implant is stable enough at placement. If that is not safe, we explain the staged timeline.'],
                    ['question' => 'Am I too old for an implant?', 'answer' => 'Age alone is not the deciding factor. Gum health, bone, healing capacity and medical history matter more.'],
                ],
                'cta_heading' => 'Find out if it is right for you.',
                'cta_heading_accent' => 'right',
                'cta_body' => 'The consultation is a scan and a conversation. You leave with a written plan and no obligation to go ahead.',
                'whatsapp_number' => '919820000000',
                'whatsapp_message' => "Hi, I'd like to ask about dental implants.",
                'phone' => '+912226000000',
                'seo_title' => "Dental Implants - Dr. Pushpa Patel's Dental Clinic",
                'seo_description' => 'Dental implants with CBCT planning, guided placement and ceramic crowns at Dr. Pushpa Patel Dental Clinic.',
            ],
            [
                'sort_order' => 3,
                'is_active' => true,
                'slug' => 'invisible-aligners',
                'tone' => 'gold',
                'home_title' => 'Invisible Aligners',
                'home_subtitle' => 'Straight teeth, quietly.',
                'home_description' => 'Scan-to-plan in a single visit, with a 3D simulation of your finished bite before you commit to the first tray.',
                'home_image' => '/assets/smile-closeup.jpg',
                'home_image_alt' => 'A close view of an aligned smile',
                'home_icon_svg' => '<rect x="3" y="8" width="18" height="8" rx="4"/><path d="M8 8v8M12 8v8M16 8v8"/>',
                'category' => 'Orthodontic care',
                'title' => 'Invisible Aligners',
                'title_accent' => 'Aligners',
                'tagline' => 'Straight teeth, quietly.',
                'summary' => 'Clear removable trays planned from a digital scan, designed to move teeth in small controlled steps without fixed metal braces.',
                'hero_image' => '/assets/smile-closeup.jpg',
                'hero_image_alt' => 'A close view of an aligned smile',
                'facts' => [
                    ['label' => 'Planning visit', 'value' => '45-60 min'],
                    ['label' => 'Typical wear', 'value' => '20-22 hrs/day'],
                    ['label' => 'Check-ins', 'value' => 'Every 6-8 wks'],
                    ['label' => 'Retainers', 'value' => 'After finish'],
                ],
                'overview_eyebrow' => 'What it is',
                'overview_heading' => 'A straighter smile planned before trays begin.',
                'overview_heading_accent' => 'planned',
                'overview_lede' => 'The scan lets you see the intended movement and final bite before you decide whether aligners are right for you.',
                'overview_body' => "Invisible aligners are a sequence of clear trays. Each tray applies gentle pressure to move selected teeth a small amount before the next tray takes over.\n\nThe first appointment is a scan, photographs and bite assessment. From that information, a digital plan shows the movement sequence and expected finish.\n\nThe trays are removable for eating and brushing, but the result depends on wear time. Aligners work best when the plan is simple enough for clear trays and the patient is consistent enough to wear them.",
                'overview_image' => '/assets/planning.jpg',
                'overview_image_alt' => 'Digital smile and bite planning on screen',
                'overview_caption' => 'The planned movement is reviewed before trays are ordered.',
                'suitability_eyebrow' => 'Suitability',
                'suitability_heading' => 'Who this works for.',
                'suitability_heading_accent' => 'works',
                'suitability_lede' => 'Aligners are discreet, but they are not a shortcut. The right case selection matters.',
                'suitable_for' => [
                    ['text' => 'Mild to moderate crowding or spacing'],
                    ['text' => 'Relapse after previous braces'],
                    ['text' => 'Adults who want a removable option'],
                    ['text' => 'Patients who can wear trays most of the day'],
                    ['text' => 'Bites that can be corrected without complex fixed appliances'],
                ],
                'not_suitable' => [
                    ['text' => 'Severe bite problems that need specialist orthodontics'],
                    ['text' => 'Untreated cavities or gum inflammation'],
                    ['text' => 'Patients unable to wear trays consistently'],
                    ['text' => 'Cases where jaw growth or skeletal correction is the main issue'],
                ],
                'process_eyebrow' => 'Step by step',
                'process_heading' => 'From scan to final retainers.',
                'process_heading_accent' => 'retainers',
                'process_lede' => 'The digital plan matters as much as the trays. Every stage is checked against the intended bite.',
                'steps' => [
                    ['title' => 'Scan and records', 'duration' => '45-60 minutes', 'body' => 'We take a digital scan, photographs and bite records, then check gum and tooth health before planning movement.'],
                    ['title' => '3D simulation', 'duration' => 'Planning stage', 'body' => 'You review the proposed movement, expected timeline and any attachments needed before approving the trays.'],
                    ['title' => 'Tray fitting', 'duration' => '30 minutes', 'body' => 'The first trays are fitted, wear instructions are explained, and any tooth-coloured attachments are placed if the plan needs them.'],
                    ['title' => 'Progress reviews', 'duration' => 'Every 6-8 weeks', 'body' => 'We check tracking, comfort and bite changes. Refinements are planned if teeth are not moving as expected.'],
                    ['title' => 'Retainers', 'duration' => 'After completion', 'body' => 'Retainers hold the result once active movement is finished. Without them, teeth can drift back.'],
                ],
                'faq_eyebrow' => 'Questions',
                'faq_heading' => 'The things people actually ask.',
                'faq_heading_accent' => 'ask',
                'faq_lede' => 'The most important question is not whether aligners are invisible. It is whether they can do the movement your bite needs.',
                'faqs' => [
                    ['question' => 'How many hours a day do I need to wear them?', 'answer' => 'Most plans need 20 to 22 hours a day. Removing trays too often is the commonest reason treatment slows down.'],
                    ['question' => 'Will aligners affect speech?', 'answer' => 'There can be a short adjustment period. Most patients adapt within a few days.'],
                    ['question' => 'Can I eat with aligners in?', 'answer' => 'No. Remove them for meals, brush or rinse before replacing them, and avoid hot drinks while wearing trays.'],
                    ['question' => 'Are aligners painful?', 'answer' => 'Each new tray can feel tight for a day or two. It should feel like pressure, not sharp pain.'],
                ],
                'cta_heading' => 'Find out if it is right for you.',
                'cta_heading_accent' => 'right',
                'cta_body' => 'Book a scan appointment and review the planned finish before committing to treatment.',
                'whatsapp_number' => '919820000000',
                'whatsapp_message' => "Hi, I'd like to ask about invisible aligners.",
                'phone' => '+912226000000',
                'seo_title' => "Invisible Aligners - Dr. Pushpa Patel's Dental Clinic",
                'seo_description' => 'Invisible aligners with digital scan planning and 3D bite simulation at Dr. Pushpa Patel Dental Clinic.',
            ],
            [
                'sort_order' => 4,
                'is_active' => true,
                'slug' => 'smile-design',
                'tone' => 'mint',
                'home_title' => 'Smile Design',
                'home_subtitle' => 'Designed before it is made.',
                'home_description' => 'Your new smile is mocked up in resin and worn home for a week — you approve the shape in your own mirror, not ours.',
                'home_image' => '/assets/whitening.jpg',
                'home_image_alt' => 'A shade-matching whitening treatment',
                'home_icon_svg' => '<circle cx="12" cy="12" r="3.2"/><path d="M12 3v2.4M12 18.6V21M3 12h2.4M18.6 12H21M5.6 5.6l1.7 1.7M16.7 16.7l1.7 1.7M18.4 5.6l-1.7 1.7M7.3 16.7l-1.7 1.7"/>',
                'category' => 'Cosmetic dentistry',
                'title' => 'Smile Design',
                'title_accent' => 'Design',
                'tagline' => 'Designed before it is made.',
                'summary' => 'A planned cosmetic workflow for tooth colour, proportion and shape, previewed before permanent treatment begins.',
                'hero_image' => '/assets/whitening.jpg',
                'hero_image_alt' => 'A shade-matching whitening treatment',
                'facts' => [
                    ['label' => 'Planning visit', 'value' => '60 minutes'],
                    ['label' => 'Preview', 'value' => 'Mock-up'],
                    ['label' => 'Common care', 'value' => 'Veneers/crowns'],
                    ['label' => 'Approval', 'value' => 'Before finish'],
                ],
                'overview_eyebrow' => 'What it is',
                'overview_heading' => 'A smile previewed before it is permanent.',
                'overview_heading_accent' => 'previewed',
                'overview_lede' => 'Smile design is a planning process, not a single material. The shape is tested before the final ceramic or composite work is made.',
                'overview_body' => "The first stage is diagnosis: photographs, bite records, shade selection and a conversation about what should change and what should stay natural.\n\nA digital or resin mock-up lets you see the proposed length, width and curve of the teeth in your own face. This is where the design is adjusted.\n\nThe final treatment may be whitening, bonding, veneers, crowns or a combination. The point is that each step follows an approved plan rather than chasing a generic smile.",
                'overview_image' => '/assets/smile-before.jpg',
                'overview_image_alt' => 'A close view of a smile before cosmetic planning',
                'overview_caption' => 'The design is judged in the face, not only on a computer screen.',
                'suitability_eyebrow' => 'Suitability',
                'suitability_heading' => 'Who this works for.',
                'suitability_heading_accent' => 'works',
                'suitability_lede' => 'Cosmetic work lasts longer when the bite, gums and tooth structure are part of the plan.',
                'suitable_for' => [
                    ['text' => 'Teeth with uneven shape, size or edges'],
                    ['text' => 'Discolouration that whitening alone cannot correct'],
                    ['text' => 'Old visible fillings or worn front teeth'],
                    ['text' => 'Patients who want to preview the design before committing'],
                    ['text' => 'Smile changes that need both colour and proportion planning'],
                ],
                'not_suitable' => [
                    ['text' => 'Active gum disease or untreated decay'],
                    ['text' => 'Heavy grinding that has not been controlled'],
                    ['text' => 'Unrealistic colour or shape expectations'],
                    ['text' => 'Bite problems that need orthodontic correction first'],
                ],
                'process_eyebrow' => 'Step by step',
                'process_heading' => 'From photographs to approved smile.',
                'process_heading_accent' => 'approved',
                'process_lede' => 'The design is refined before permanent treatment, so the final work is not a surprise.',
                'steps' => [
                    ['title' => 'Smile analysis', 'duration' => '60 minutes', 'body' => 'We photograph the smile, assess tooth display, gum levels, bite and colour, then discuss what outcome should look natural for you.'],
                    ['title' => 'Digital design', 'duration' => 'Planning stage', 'body' => 'The proposed tooth shape and proportions are planned from the records and checked against the face.'],
                    ['title' => 'Mock-up preview', 'duration' => 'One visit', 'body' => 'A trial version is placed over the teeth so you can see the shape before permanent work starts.'],
                    ['title' => 'Final treatment', 'duration' => 'Varies by plan', 'body' => 'Whitening, bonding, veneers or crowns are completed according to the approved design.'],
                    ['title' => 'Maintenance', 'duration' => 'Review visits', 'body' => 'We review the bite, polish margins and advise on night guards if grinding could affect the result.'],
                ],
                'faq_eyebrow' => 'Questions',
                'faq_heading' => 'The things people actually ask.',
                'faq_heading_accent' => 'ask',
                'faq_lede' => 'Good smile design should still look like you. The preview visit is where that balance is tested.',
                'faqs' => [
                    ['question' => 'Will my teeth need to be cut?', 'answer' => 'It depends on the plan. Some cases can be improved with whitening and bonding; others need veneers or crowns. We explain the tooth preparation before you decide.'],
                    ['question' => 'Can I see the result before treatment?', 'answer' => 'Yes. A digital preview or resin mock-up is used so the proposed shape can be reviewed and adjusted.'],
                    ['question' => 'How white should I go?', 'answer' => 'The shade is chosen with your skin tone, existing teeth and the amount of dentistry planned. Natural usually ages better than extreme white.'],
                    ['question' => 'How long does smile design last?', 'answer' => 'Longevity depends on the material, bite, grinding habits and maintenance. Ceramic and composite have different lifespans, which are discussed in the plan.'],
                ],
                'cta_heading' => 'Find out if it is right for you.',
                'cta_heading_accent' => 'right',
                'cta_body' => 'Bring references if you have them. The consultation turns them into a realistic clinical plan.',
                'whatsapp_number' => '919820000000',
                'whatsapp_message' => "Hi, I'd like to ask about smile design.",
                'phone' => '+912226000000',
                'seo_title' => "Smile Design - Dr. Pushpa Patel's Dental Clinic",
                'seo_description' => 'Smile design with digital planning, mock-up previews, whitening, bonding, veneers and crowns at Dr. Pushpa Patel Dental Clinic.',
            ],
            [
                'sort_order' => 5,
                'is_active' => true,
                'slug' => 'jaw-joint-and-tmd',
                'tone' => 'violet',
                'home_title' => 'Jaw Joint & TMD',
                'home_subtitle' => 'Align, relieve, smile.',
                'home_description' => 'Clicking, locking, morning headaches and unexplained ear pain — worked up with joint imaging, muscle mapping and splint therapy.',
                'home_image' => '/assets/portrait-warm.jpg',
                'home_image_alt' => 'A patient after jaw joint therapy',
                'home_icon_svg' => '<path d="M12 2v20M7 6h10M6.5 11h11M8 16h8"/>',
                'category' => 'Jaw joint care',
                'title' => 'Jaw Joint & TMD',
                'title_accent' => 'TMD',
                'tagline' => 'Align, relieve, smile.',
                'summary' => 'Assessment-led care for jaw clicking, locking, facial muscle pain, morning headaches and bite-related strain.',
                'hero_image' => '/assets/portrait-warm.jpg',
                'hero_image_alt' => 'A patient after jaw joint therapy',
                'facts' => [
                    ['label' => 'Assessment', 'value' => 'Bite + muscles'],
                    ['label' => 'Common aid', 'value' => 'Splint therapy'],
                    ['label' => 'Review cycle', 'value' => '2-6 weeks'],
                    ['label' => 'Goal', 'value' => 'Reduce strain'],
                ],
                'overview_eyebrow' => 'What it is',
                'overview_heading' => 'Jaw pain treated from the joint and the bite.',
                'overview_heading_accent' => 'joint',
                'overview_lede' => 'TMD symptoms can come from the jaw joint, chewing muscles, bite overload or habits such as clenching.',
                'overview_body' => "Jaw joint care starts with mapping the symptoms. Clicking, locking, morning headaches, sore chewing muscles and ear-area pain are assessed together rather than treated as separate complaints.\n\nWe check jaw movement, muscle tenderness, tooth wear, bite contacts and any history of grinding or trauma. Imaging is advised when the joint itself needs a closer look.\n\nTreatment may include a stabilisation splint, habit changes, bite adjustments, physiotherapy referral or staged dental work where the bite is contributing to the problem.",
                'overview_image' => '/assets/consult-family.jpg',
                'overview_image_alt' => 'A dentist discussing symptoms and treatment options with a patient',
                'overview_caption' => 'Jaw joint treatment is planned from symptoms, bite records and muscle findings.',
                'suitability_eyebrow' => 'Suitability',
                'suitability_heading' => 'Who this works for.',
                'suitability_heading_accent' => 'works',
                'suitability_lede' => 'The first visit is diagnostic. It separates dental bite strain from problems that need medical or specialist review.',
                'suitable_for' => [
                    ['text' => 'Jaw clicking, popping or locking'],
                    ['text' => 'Morning headaches or jaw muscle soreness'],
                    ['text' => 'Tooth wear from clenching or grinding'],
                    ['text' => 'Bite discomfort after dental changes'],
                    ['text' => 'Ear-area pain where ENT causes have been ruled out'],
                ],
                'not_suitable' => [
                    ['text' => 'Sudden swelling, fever or infection symptoms'],
                    ['text' => 'Acute trauma that needs urgent medical imaging'],
                    ['text' => 'Neurological symptoms such as numbness or facial weakness'],
                    ['text' => 'Pain that clearly needs medical specialist management first'],
                ],
                'process_eyebrow' => 'Step by step',
                'process_heading' => 'From symptoms to a calmer bite.',
                'process_heading_accent' => 'calmer',
                'process_lede' => 'The plan is reviewed in stages because jaw joint symptoms usually change gradually, not overnight.',
                'steps' => [
                    ['title' => 'Symptom mapping', 'duration' => '30-45 minutes', 'body' => 'We document when pain starts, what triggers it, and whether clicking, locking or grinding is part of the pattern.'],
                    ['title' => 'Bite and muscle exam', 'duration' => 'At first visit', 'body' => 'Jaw movement, muscle tenderness, tooth wear and bite contacts are checked together.'],
                    ['title' => 'Splint or first-stage care', 'duration' => '2-3 weeks', 'body' => 'A splint, exercises or habit changes may be started to reduce overload and protect the teeth.'],
                    ['title' => 'Review and adjustment', 'duration' => '2-6 weeks', 'body' => 'Symptoms are reviewed, the splint is adjusted if needed, and the next stage is decided from response.'],
                    ['title' => 'Long-term plan', 'duration' => 'As needed', 'body' => 'If the bite or worn teeth are contributing, restorative or orthodontic options are discussed only after symptoms settle.'],
                ],
                'faq_eyebrow' => 'Questions',
                'faq_heading' => 'The things people actually ask.',
                'faq_heading_accent' => 'ask',
                'faq_lede' => 'Jaw joint care needs diagnosis first. A splint is useful only when it matches the cause.',
                'faqs' => [
                    ['question' => 'Is clicking always serious?', 'answer' => 'No. Some clicks are painless and stable. Clicking with pain, locking or reduced opening should be assessed.'],
                    ['question' => 'Will a night guard fix it?', 'answer' => 'A well-planned splint can reduce overload, but the design depends on the bite and symptoms. A generic guard may not be enough.'],
                    ['question' => 'Can jaw pain cause headaches?', 'answer' => 'Clenching and chewing muscle strain can contribute to morning headaches. Other medical causes should be considered when symptoms do not fit a dental pattern.'],
                    ['question' => 'How quickly does TMD improve?', 'answer' => 'Some patients feel relief within weeks, while long-standing symptoms take longer. Reviews are used to adjust the plan.'],
                ],
                'cta_heading' => 'Find out if it is right for you.',
                'cta_heading_accent' => 'right',
                'cta_body' => 'Bring any previous scans, guards or bite splints to the consultation so we can see what has already been tried.',
                'whatsapp_number' => '919820000000',
                'whatsapp_message' => "Hi, I'd like to ask about jaw joint and TMD care.",
                'phone' => '+912226000000',
                'seo_title' => "Jaw Joint & TMD - Dr. Pushpa Patel's Dental Clinic",
                'seo_description' => 'Jaw joint and TMD care for clicking, locking, headaches, clenching and bite strain at Dr. Pushpa Patel Dental Clinic.',
            ],
            [
                'sort_order' => 6,
                'is_active' => true,
                'slug' => 'kids-dentistry',
                'tone' => 'blush',
                'home_title' => "Kids' Dentistry",
                'home_subtitle' => 'First visits without fear.',
                'home_description' => 'A mirror, a ride in the chair and a sticker. No treatment at all until the room has stopped being frightening.',
                'home_image' => '/assets/pediatric.jpg',
                'home_image_alt' => 'A child at a first dental visit',
                'home_icon_svg' => '<circle cx="12" cy="12" r="9"/><path d="M8.5 14.5a4.5 4.5 0 007 0M9 9.5h.01M15 9.5h.01"/>',
                'category' => 'Children dentistry',
                'title' => "Kids' Dentistry",
                'title_accent' => 'Dentistry',
                'tagline' => 'First visits without fear.',
                'summary' => 'Gentle dental visits for children, focused on trust, prevention and simple treatment only when the child is ready.',
                'hero_image' => '/assets/pediatric.jpg',
                'hero_image_alt' => 'A child at a first dental visit',
                'facts' => [
                    ['label' => 'First visit', 'value' => 'Familiarisation'],
                    ['label' => 'Prevention', 'value' => 'Fluoride/sealants'],
                    ['label' => 'Parent role', 'value' => 'In the room'],
                    ['label' => 'Goal', 'value' => 'No fear'],
                ],
                'overview_eyebrow' => 'What it is',
                'overview_heading' => 'A dental room that becomes familiar first.',
                'overview_heading_accent' => 'familiar',
                'overview_lede' => 'Children do better when the first visit is not rushed into treatment. The chair, mirror and sounds are introduced slowly.',
                'overview_body' => "Kids' dentistry is prevention, habit guidance and treatment paced around the child. The first appointment may be only a look, a count of teeth and a ride in the chair.\n\nWhen treatment is needed, we explain it in child-friendly language and keep parents involved. Small wins matter because they decide how a child feels about dentistry for years.\n\nThe regular plan includes cleaning advice, fluoride where appropriate, sealants for deep grooves, cavity checks and growth monitoring.",
                'overview_image' => '/assets/pediatric-2.jpg',
                'overview_image_alt' => 'A child smiling during a dental visit',
                'overview_caption' => 'Early visits are designed to make the clinic feel predictable before treatment is needed.',
                'suitability_eyebrow' => 'Suitability',
                'suitability_heading' => 'Who this works for.',
                'suitability_heading_accent' => 'works',
                'suitability_lede' => 'The earlier a child meets the dental room, the easier prevention becomes.',
                'suitable_for' => [
                    ['text' => 'A first dental visit or routine check-up'],
                    ['text' => 'Children with early cavities or sensitivity'],
                    ['text' => 'Parents needing brushing, diet and fluoride guidance'],
                    ['text' => 'Fissure sealants for deep grooves in molars'],
                    ['text' => 'Children anxious from a previous dental experience'],
                ],
                'not_suitable' => [
                    ['text' => 'Facial swelling or fever, which needs urgent assessment'],
                    ['text' => 'Dental trauma with a knocked-out permanent tooth, which is an emergency'],
                    ['text' => 'Children who need hospital-based sedation or general anaesthesia'],
                    ['text' => 'Complex orthodontic growth issues needing specialist referral'],
                ],
                'process_eyebrow' => 'Step by step',
                'process_heading' => 'From chair ride to confident visits.',
                'process_heading_accent' => 'confident',
                'process_lede' => 'The appointment is built around trust first, then prevention, then treatment only when needed.',
                'steps' => [
                    ['title' => 'Meet the room', 'duration' => 'First visit', 'body' => 'The child sees the mirror, chair, light and suction. Treatment is not forced during a familiarisation visit.'],
                    ['title' => 'Count and check', 'duration' => '10-20 minutes', 'body' => 'We count teeth, check gums, look for cavities and explain findings to the parent in simple terms.'],
                    ['title' => 'Prevention plan', 'duration' => 'Same visit', 'body' => 'Brushing technique, fluoride, diet and sealants are discussed according to age and risk.'],
                    ['title' => 'Gentle treatment if needed', 'duration' => 'Planned visit', 'body' => 'Small fillings or other care are scheduled only after the child understands the steps and can cooperate safely.'],
                    ['title' => 'Recall rhythm', 'duration' => 'Every 6 months', 'body' => 'Routine reviews help children see dentistry as normal maintenance rather than a place they visit only when something hurts.'],
                ],
                'faq_eyebrow' => 'Questions',
                'faq_heading' => 'The things parents actually ask.',
                'faq_heading_accent' => 'parents',
                'faq_lede' => 'Bring questions about brushing, sweets, thumb sucking, bottle habits or tooth eruption. They are part of the appointment.',
                'faqs' => [
                    ['question' => 'When should my child first see a dentist?', 'answer' => 'A first visit is useful when the first teeth arrive or by the first birthday. It can be short and focused on advice.'],
                    ['question' => 'Do baby teeth really need fillings?', 'answer' => 'Sometimes, yes. Baby teeth hold space, help chewing and speech, and can cause pain or infection if decay is ignored.'],
                    ['question' => 'Can I stay in the room?', 'answer' => 'Yes. Parents are part of the visit, especially for younger children.'],
                    ['question' => 'What if my child is scared?', 'answer' => 'We slow down. The first goal may simply be to sit in the chair and leave happy, then build from there.'],
                ],
                'cta_heading' => 'Find out if it is right for your child.',
                'cta_heading_accent' => 'child',
                'cta_body' => 'Book a calm first visit before there is pain. Prevention is easier when the clinic already feels familiar.',
                'whatsapp_number' => '919820000000',
                'whatsapp_message' => "Hi, I'd like to ask about kids' dentistry.",
                'phone' => '+912226000000',
                'seo_title' => "Kids' Dentistry - Dr. Pushpa Patel's Dental Clinic",
                'seo_description' => "Kids' dentistry for first visits, prevention, fluoride, sealants and gentle child dental care at Dr. Pushpa Patel Dental Clinic.",
            ],
        ];
    }

    /**
     * @param  array<string, mixed>  $treatment
     * @return array<string, mixed>
     */
    private function withSeoDefaults(array $treatment): array
    {
        $title = $treatment['seo_title'] ?? "{$treatment['title']} - Dr. Pushpa Patel's Dental Clinic";
        $description = $treatment['seo_description'] ?? $this->plainText($treatment['summary'] ?? '');
        $image = $treatment['hero_image'] ?? $treatment['home_image'] ?? '';
        $imageAlt = $treatment['hero_image_alt'] ?? $treatment['home_image_alt'] ?? '';
        $keyword = strtolower((string) $treatment['home_title']);

        return [
            ...$treatment,
            'seo_canonical_url' => $treatment['seo_canonical_url'] ?? null,
            'seo_focus_keyword' => $treatment['seo_focus_keyword'] ?? $keyword,
            'seo_secondary_keywords' => $treatment['seo_secondary_keywords'] ?? implode(', ', [
                "{$treatment['home_title']} Bandra West",
                "{$treatment['home_title']} Mumbai",
                "Dr Pushpa Patel {$treatment['home_title']}",
            ]),
            'seo_robots_index' => $treatment['seo_robots_index'] ?? true,
            'seo_robots_follow' => $treatment['seo_robots_follow'] ?? true,
            'seo_breadcrumb_label' => $treatment['seo_breadcrumb_label'] ?? $treatment['home_title'],
            'seo_og_title' => $treatment['seo_og_title'] ?? $title,
            'seo_og_description' => $treatment['seo_og_description'] ?? $description,
            'seo_og_image' => $treatment['seo_og_image'] ?? $image,
            'seo_og_image_alt' => $treatment['seo_og_image_alt'] ?? $imageAlt,
            'seo_twitter_card' => $treatment['seo_twitter_card'] ?? 'summary_large_image',
            'seo_twitter_title' => $treatment['seo_twitter_title'] ?? $title,
            'seo_twitter_description' => $treatment['seo_twitter_description'] ?? $description,
            'seo_twitter_image' => $treatment['seo_twitter_image'] ?? $image,
            'seo_enable_schema' => $treatment['seo_enable_schema'] ?? true,
            'seo_schema_type' => $treatment['seo_schema_type'] ?? $this->schemaTypeFor($treatment['slug']),
            'seo_schema_name' => $treatment['seo_schema_name'] ?? $treatment['title'],
            'seo_schema_description' => $treatment['seo_schema_description'] ?? $description,
        ];
    }

    private function schemaTypeFor(string $slug): string
    {
        return match ($slug) {
            'jaw-joint-tmd' => 'MedicalTherapy',
            default => 'MedicalProcedure',
        };
    }

    private function plainText(string $value): string
    {
        return trim((string) preg_replace('/\s+/', ' ', strip_tags($value)));
    }
}
